language: java
jdk:
  - oraclejdk7
install: 
  - mvn clean install -DskipTests=true
  - mvn clean install -DskipTests=true -P yarn

notifications:
  email:
    recipients:
      - dev@collaborate.jumbune.org
    on_success: change # default: change
    on_failure: change # default: always
