!!org.jumbune.common.yaml.config.YamlConfig
classpath:
  jumbuneSupplied: null
  userSupplied: {excludes: null, files: null, folders: null, source: -1}
dataValidation:
  fieldSeparator: ','
  fieldValidationList:
  - {dataType: double_type, fieldNumber: 0, nullCheck: notNull, regex: '^[1-9][0-9]{8}'}
  - {dataType: double_type, fieldNumber: 1, nullCheck: notNull, regex: '^[1-9][0-9]{3}'}
  - {dataType: int_type, fieldNumber: 2, nullCheck: notNull, regex: '^[1-9][0-9]{9}'}
  - {dataType: int_type, fieldNumber: 3, nullCheck: notNull, regex: '^[1-9][0-9]{3}'}
  - {dataType: int_type, fieldNumber: 4, nullCheck: notNull, regex: null}
  - {dataType: int_type, fieldNumber: 5, nullCheck: notNull, regex: null}
  - {dataType:  , fieldNumber: 6, nullCheck: mustBeNull, regex: null}
  numOfFields: 7
  recordSeparator: '

    '
debugAnalysis: 'FALSE'
debuggerConf:
  fieldSeparator: null
  hDFSSourcePath: null
  logLevel: {instrumentRegex: 'FALSE', instrumentUserDefValidate: 'FALSE'}
  maxIfBlockNestingLevel: 0
  recordSeparator: null
  sampleToggle: null
  useEntireWorkingSet: null
distributedHDFSPath: null
doNotInstrument: null
enableDataValidation: 'TRUE'
enableStaticJobProfiling: 'FALSE'
existingJobName: null
hadoopJobProfile: 'FALSE'
hdfsInputPath: /Jumbune/sensordata
includeClassJar: 'FALSE'
inputFile: null
jobs: []
jumbuneJobName: SensorDataSample
mapperSuperClasses: null
master: {agentPort: '5567', dsaFile: null, host: name.node.ip, jobTrackerJmxPort: '5680',
  location: null, nameNodeJmxPort: '5677', receiveDirectory: null, rsaFile: user.home.directory/.ssh/id_rsa,
  user: user.name}
partitionerSampleInterval: 0
profilingParams: {dataNodeJmxPort: null, jobTrackerJmxPort: null, mapers: 0-1, masterJmxPort: null,
  reducers: 0-1, statsInterval: 5000, taskTrackerJmxPort: null}
reducerSuperClasses: null
regexValidations: []
runJobFromJumbune: 'FALSE'
sJumbuneHome: user.home.directory/tmp/jHome
slaveParam: {dataNodeJmxPort: '5679', taskTrackerJmxPort: '5678'}
slaves:
- enableHostRange: null
  hostRangeFromValue: null
  hostRangeToValue: null
  hosts: [data.node.ip]
  location: null
  unavailableHosts: null
  user: user.name
userValidations: []
